// Code generated by go-swagger; DO NOT EDIT.

// Package restapi RESTAPI-server-made-of-Golang
//
//  Go HTTP server with Swagger endpoints definition
//  Schemes:
//    http
//  Host: localhost
//  BasePath: /
//  Version: 0.1.0
//
//  Consumes:
//    - application/json
//
//  Produces:
//    - image/png
//    - application/json
//    - text/plain
//
// swagger:meta
package restapi
