// Code generated by go-swagger; DO NOT EDIT.

package restapi

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
)

var (
	// SwaggerJSON embedded version of the swagger document used at generation time
	SwaggerJSON json.RawMessage
	// FlatSwaggerJSON embedded flattened version of the swagger document used at generation time
	FlatSwaggerJSON json.RawMessage
)

func init() {
	SwaggerJSON = json.RawMessage([]byte(`{
  "consumes": [
    "application/json"
  ],
  "produces": [
    "application/json"
  ],
  "schemes": [
    "http"
  ],
  "swagger": "2.0",
  "info": {
    "description": "Go HTTP server with Swagger endpoints definition",
    "title": "RESTAPI-server-made-of-Golang",
    "version": "0.1.0"
  },
  "paths": {
    "/gopher/{name}": {
      "get": {
        "description": "gopher image",
        "produces": [
          "image/png"
        ],
        "parameters": [
          {
            "type": "string",
            "description": "What gopher image you want?",
            "name": "name",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "return gopher image",
            "schema": {
              "type": "file"
            }
          }
        }
      }
    },
    "/health": {
      "get": {
        "produces": [
          "text/plain"
        ],
        "operationId": "checkHealth",
        "responses": {
          "200": {
            "description": "Health checked message",
            "schema": {
              "type": "string",
              "enum": [
                "OK"
              ]
            }
          }
        }
      }
    },
    "/hello/{user}": {
      "get": {
        "description": "Returns a greeting to a user",
        "parameters": [
          {
            "type": "string",
            "description": "Username to greet",
            "name": "user",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "return greeting",
            "schema": {
              "type": "string"
            }
          },
          "400": {
            "description": "Something wrong"
          }
        }
      }
    }
  }
}`))
	FlatSwaggerJSON = json.RawMessage([]byte(`{
  "consumes": [
    "application/json"
  ],
  "produces": [
    "application/json"
  ],
  "schemes": [
    "http"
  ],
  "swagger": "2.0",
  "info": {
    "description": "Go HTTP server with Swagger endpoints definition",
    "title": "RESTAPI-server-made-of-Golang",
    "version": "0.1.0"
  },
  "paths": {
    "/gopher/{name}": {
      "get": {
        "description": "gopher image",
        "produces": [
          "image/png"
        ],
        "parameters": [
          {
            "type": "string",
            "description": "What gopher image you want?",
            "name": "name",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "return gopher image",
            "schema": {
              "type": "file"
            }
          }
        }
      }
    },
    "/health": {
      "get": {
        "produces": [
          "text/plain"
        ],
        "operationId": "checkHealth",
        "responses": {
          "200": {
            "description": "Health checked message",
            "schema": {
              "type": "string",
              "enum": [
                "OK"
              ]
            }
          }
        }
      }
    },
    "/hello/{user}": {
      "get": {
        "description": "Returns a greeting to a user",
        "parameters": [
          {
            "type": "string",
            "description": "Username to greet",
            "name": "user",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "return greeting",
            "schema": {
              "type": "string"
            }
          },
          "400": {
            "description": "Something wrong"
          }
        }
      }
    }
  }
}`))
}
